--- #YAML:1.0
name:               Net-Amazon-MechanicalTurk
version:            1.01_01
abstract:           Amazon Mechanical Turk SDK for Perl
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_SHA1:  0
    LWP:                0
    MIME::Base64:       0
    Test::More:         0
    URI::Escape:        0
    XML::Parser:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
